# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ButtonAnimationSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ButtonAnimationSample

  target 'ButtonAnimationSampleTests' do

    inherit! :search_paths
    # Pods for testing
  end

  target 'ButtonAnimationSampleUITests' do
    # Pods for testing
  end

end
